// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQLmjBzK1fm5fXspm88auzy4GOv6oufU',
    appId: '1:704482320936:web:b10e1a185459554d980b1d',
    messagingSenderId: '704482320936',
    projectId: 'driveresq-app',
    authDomain: 'driveresq-app.firebaseapp.com',
    storageBucket: 'driveresq-app.firebasestorage.app',
    measurementId: 'G-92N3M5JP8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs48xcaWt_34rhxJidYuxqijTlXfC6F8A',
    appId: '1:704482320936:android:620c95ffbc48f34e980b1d',
    messagingSenderId: '704482320936',
    projectId: 'driveresq-app',
    storageBucket: 'driveresq-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh0CqRrIfOBNxV6N8i5ddN05wnZlPllBU',
    appId: '1:704482320936:ios:73b39d2a6bccf758980b1d',
    messagingSenderId: '704482320936',
    projectId: 'driveresq-app',
    storageBucket: 'driveresq-app.firebasestorage.app',
    iosBundleId: 'com.example.driveresqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh0CqRrIfOBNxV6N8i5ddN05wnZlPllBU',
    appId: '1:704482320936:ios:73b39d2a6bccf758980b1d',
    messagingSenderId: '704482320936',
    projectId: 'driveresq-app',
    storageBucket: 'driveresq-app.firebasestorage.app',
    iosBundleId: 'com.example.driveresqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQLmjBzK1fm5fXspm88auzy4GOv6oufU',
    appId: '1:704482320936:web:6b18f7e6fb3132ef980b1d',
    messagingSenderId: '704482320936',
    projectId: 'driveresq-app',
    authDomain: 'driveresq-app.firebaseapp.com',
    storageBucket: 'driveresq-app.firebasestorage.app',
    measurementId: 'G-98FJ3YC272',
  );
}
